# Generated by Django 4.0.4 on 2022-04-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCpder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
