# Generated by Django 4.0.4 on 2022-04-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCpder', '0003_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
